### ISSUE TITLE
getAttributes segfault

### ISSUE THREAD

**Issue by ArgonAlex** [xxoo/node-fswin#21]
First of all, congratulations on the N-API release! It looks like it was a pretty large effort!

I do have one issue to report however. Any calls to getAttributes() results in a segmentation fault. I'm also using setAttributes() which seems to work, and getAttributesSync() also seems to work.

```
$ node -e "require('fswin').getAttributes('src', function (result) { })"
Segmentation fault
```

Node 10.10.0
fswin 3.18.909

**Comment by xxoo** [comment]
thanks! there was a stupid mistake, and it should be fixed now.
please update fswin to try it out

**Comment by ArgonAlex** [comment]
Hmm I'm still getting a segfault. Just noticed it is only happening when running node in a Cygwin shell though. Regular CMD works.

**Comment by xxoo** [comment]
sorry but it works for me. there was a pointer error that may cause segfault. but it should be already fixed. perhaps i need more detail to reproduce the error
![image](https://user-images.githubusercontent.com/1268383/45671228-7e480c80-bb57-11e8-832a-f0afb341c5d8.png)
